import Head from 'next/head'

export default function Home({ posts }) {
  console.log(`Loaded: ${posts.total} item(s)`)
  return (
    <>
      <Head>
        <title>EBDM Blog - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-white">
        <div className="max-w-7xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
          <div className="text-center">
            <h2 className="text-base font-semibold text-indigo-600 tracking-wide uppercase">EBDM Blog</h2>
            <p className="mt-1 text-4xl font-extrabold text-gray-900 sm:text-5xl sm:tracking-tight lg:text-6xl">
              Welcome to my blog
            </p>
            <p className="max-w-xl mt-5 mx-auto text-xl text-gray-500">
              Home of my mad ramblings
            </p>
          </div>
        </div>
      </div>

      <Posts items={posts.items}/>
    </>
  )
}

import { fetchRestAPI, getAllPosts } from "../lib/contentful"
import Link from 'next/link'

export async function getStaticProps({ params }) {
  const posts = await fetchRestAPI({ 
    type: 'blogPost'
  })

  return {
    props: {
      posts: posts
    }
  }
}

function Posts({ items }) {
  return (
    <div className="bg-white pb-10 px-4 sm:px-6 lg:pb-28 lg:px-8">
      <div className="relative max-w-lg mx-auto divide-y-2 divide-gray-200 lg:max-w-7xl">
        <div>
          <h2 className="text-3xl tracking-tight font-extrabold text-gray-900 sm:text-4xl">Recent Posts</h2>
          {/* <div className="mt-3 sm:mt-4 lg:grid lg:grid-cols-2 lg:gap-5 lg:items-center">
            <p className="text-xl text-gray-500">Sign up to be notified of new posts.</p>
            <form className="mt-6 flex flex-col sm:flex-row lg:mt-0 lg:justify-end">
              <div>
                <label htmlFor="email-address" className="sr-only">
                  Email address
                </label>
                <input
                  id="email-address"
                  name="email-address"
                  type="email"
                  autoComplete="email"
                  required
                  className="appearance-none w-full px-4 py-2 border border-gray-300 text-base rounded-md text-gray-900 bg-white placeholder-gray-500 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 lg:max-w-xs"
                  placeholder="Enter your email"
                />
              </div>
              <div className="mt-2 flex-shrink-0 w-full flex rounded-md shadow-sm sm:mt-0 sm:ml-3 sm:w-auto sm:inline-flex">
                <button
                  type="button"
                  className="w-full bg-indigo-600 px-4 py-2 border border-transparent rounded-md flex items-center justify-center text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:w-auto sm:inline-flex"
                >
                  Notify me
                </button>
              </div>
            </form>
          </div> */}
        </div>
        <div className="mt-6 pt-10 grid gap-16 lg:grid-cols-2 lg:gap-x-5 lg:gap-y-12">
          {items.map((post) => {
            const publishedAt = new Date(post.fields.publishedAt) 
            console.log(post) 
            return (
            <div key={post.fields.slug} className="hover:border-gray-400 border-transparent border-2 rounded-md p-4 hover:bg-gray-200">
              <p className="text-sm text-gray-500">
                <time dateTime={publishedAt.toLocaleString()}>{publishedAt.toLocaleString()}</time>
              </p>
              <span className="mt-2 block">
                <p className="text-xl font-semibold text-gray-900">{post.fields.title}</p>
                <p className="mt-3 text-base text-gray-500">{post.fields.description}</p>
              </span>
              <div className="mt-3">
                <Link href={`/blog/${post.fields.slug}`} passHref>
                  <a className="p-2 rounded-md text-base font-semibold text-indigo-600 hover:text-white hover:bg-indigo-500">
                    Read post
                  </a>
                </Link>
              </div>
            </div>
          )})}
        </div>
      </div>
    </div>
  )
}